
const experimental = "experimental";

const blink = (...labels: string[]) => ({ engine: "blink", engineName: "Blink", labels });
const webkit = (...labels: string[]) => ({ engine: "webkit", engineName: "WebKit", labels });
const gecko = (...labels: string[]) => ({ engine: "gecko", engineName: "Gecko", labels });

export default {
	html: [
		["modulepreload", [blink()], "https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload"],
		["MathML", [blink(experimental), webkit(), gecko()], "https://w3c.github.io/mathml-core/"],
		["<selectmenu>", [blink(experimental)], "https://open-ui.org/prototypes/selectmenu"],
		["SVG favicons", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/links.html#rel-icon"],
		["AVIF images", [blink(), webkit(experimental), gecko()], "https://aomediacodec.github.io/av1-avif/"],
		["popups", [blink(experimental)], "https://open-ui.org/components/popup.research.explainer"],
		["theme-color", [blink(), webkit()], "https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color"],
		["<fencedframe>", [blink(experimental)], "https://wicg.github.io/fenced-frame/#the-fencedframe-element"],
		["<portal>", [blink(experimental)], "https://wicg.github.io/portals/#the-portal-element"],
		["anonymous iframe", [blink(experimental)], "https://wicg.github.io/anonymous-iframe/#specification"],
		["JPEG XL images", [blink(experimental), gecko(experimental)], "https://www.spiedigitallibrary.org/conference-proceedings-of-spie/11137/111370K/JPEG-XL-next-generation-image-compression-architecture-and-coding-tools/10.1117/12.2529237.full"],
		["AV1 videos", [blink(), gecko()], "https://aomediacodec.github.io/av1-spec/"],
		["declarative shadow dom", [blink()], "https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md"],
	],
	css: [
		["nesting", [], "https://drafts.csswg.org/css-nesting-1/"],
		["backdrop-filter", [blink(), webkit(), gecko(experimental)], "https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty"],
		[":host-context()", [blink()], "https://drafts.csswg.org/css-scoping-1/#selectordef-host-context"],
		["shared element transitions (CSS)", [blink(experimental)], "https://tabatkins.github.io/specs/css-shared-element-transitions/"],
		["@property", [blink()], "https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule"],
		[":has()", [blink(experimental), webkit()], "https://drafts.csswg.org/selectors-4/#relational"],
		["viewport unit variants", [blink(experimental), webkit(), gecko()], "https://drafts.csswg.org/css-values-4/#viewport-relative-units"],
		["color-mix()", [webkit(experimental), gecko(experimental)], "https://drafts.csswg.org/css-color-5/#color-mix"],
		["relative color syntax", [webkit(experimental)], "https://drafts.csswg.org/css-color-5/#relative-colors"],
		["individual transform properties", [blink(experimental), webkit(), gecko()], "https://drafts.csswg.org/css-transforms-2/#individual-transforms"],
		["color-contrast()", [blink(experimental), webkit(experimental)], "https://drafts.csswg.org/css-color-6/#colorcontrast"],
		["media query ranges", [blink(experimental), gecko()], "https://drafts.csswg.org/mediaqueries-4/#mq-range-context"],
		["subgrid", [webkit(experimental), gecko()], "https://drafts.csswg.org/css-grid-2/#subgrids"],
		["@page", [blink(), gecko()], "https://drafts.csswg.org/css-page-3/#at-page-rule"],
		["@page margin boxes", [], "https://drafts.csswg.org/css-page-3/#margin-boxes"],
		["page-based counters", [], "https://drafts.csswg.org/css-page-3/#page-based-counters"],
		["display: two-value syntax", [webkit(), gecko()], "https://drafts.csswg.org/css-display-3/#the-display-properties"],
		["opacity percentage values", [blink(), gecko()], "https://drafts.csswg.org/css-color-4/#alpha-syntax"],
		["masonry layout", [gecko(experimental)], "https://drafts.csswg.org/css-grid-3/#masonry-layout"],
		["anchor positioning", [], "https://tabatkins.github.io/specs/css-anchor-position/"],
		["gradient color spaces", [webkit(experimental)], "https://drafts.csswg.org/css-images-4/#gradients"],
		["column combinator", [], "https://drafts.csswg.org/selectors-4/#the-column-combinator"],
		[":nth-col(), :nth-last-col()", [], "https://drafts.csswg.org/selectors-4/#the-nth-col-pseudo"],
		["@scope", [], "https://drafts.csswg.org/css-cascade-6/#scope-atrule"],
		["overflow-{block, inline}", [gecko()], "https://drafts.csswg.org/css-overflow-3/#logical"],
		["@container", [blink(experimental), webkit(experimental)], "https://drafts.csswg.org/css-contain-3/#container-rule"],
		["@container style()", [], "https://drafts.csswg.org/css-contain-3/#typedef-query-in-parens"],
		["@custom-media", [], "https://drafts.csswg.org/mediaqueries-5/#custom-mq"],
		["@scroll-timeline", [blink(experimental)], "https://drafts.csswg.org/scroll-animations-1/#scroll-timeline-at-rule"],
		["overscroll-behavior", [blink(), webkit(experimental), gecko()], "https://drafts.csswg.org/css-overscroll-1/#overscroll-behavior-properties"],
		["toggles", [], "https://tabatkins.github.io/css-toggle/"],
		["toggle()", [], "https://drafts.csswg.org/css-values-5/#toggle-notation"],
		["toggle states", [], "https://tabatkins.github.io/specs/css-toggle-states/"],
		["cascade control", [], "https://tabatkins.github.io/specs/css-cascade-control/"],
		["SVG parameters", [], "https://tabatkins.github.io/specs/svg-params/"],
		["@extend", [], "https://tabatkins.github.io/specs/css-extend-rule/#extend-rule"],
		["content-size", [], "https://tabatkins.github.io/specs/css-content-size/#content-size"],
		["@filter", [], "https://tabatkins.github.io/specs/css-filter-rule/#filter-rule"],
		["element()", [gecko()], "https://drafts.csswg.org/css-images-4/#element-notation"],
		["content-visibility", [blink()], "https://drafts.csswg.org/css-contain-2/#content-visibility"],
		["@media (scripting)", [], "https://drafts.csswg.org/mediaqueries-5/#scripting"],
		["::slotted()", [], "https://drafts.csswg.org/css-scoping-1/#slotted-pseudo"],
		["scroll-start", [], "https://drafts.csswg.org/css-scroll-snap-2/#scroll-start"],
		[":snapped", [], "https://drafts.csswg.org/css-scroll-snap-2/#snapped"],
		["{snapchanged, snapchanging} event", [], "https://drafts.csswg.org/css-scroll-snap-2/#snapchanged-and-snapchanging"],
		["hanging-punctuation", [webkit()], "https://drafts.csswg.org/css-text-3/#hanging-punctuation-property"],
		["initial-letter", [webkit()], "https://drafts.csswg.org/css-inline-3/#sizing-drop-initials"],
		["@counter-style", [blink(), gecko()], "https://drafts.csswg.org/css-counter-styles-3/#the-counter-style-rule"],
		["trigonometric functions in calc()", [webkit()], "https://drafts.csswg.org/css-values-4/#trig-funcs"],
		["exponential functions in calc()", [webkit()], "https://drafts.csswg.org/css-values-4/#exponent-funcs"],
		["sign-related functions in calc()", [], "https://drafts.csswg.org/css-values-4/#sign-funcs"],
		["src()", [], "https://drafts.csswg.org/css-values-4/#funcdef-src"],
		["clip-path: external SVGs", [gecko()], "https://drafts.fxtf.org/css-masking-1/#the-clip-path"],
		["mask-composite", [webkit(), gecko()], "https://drafts.fxtf.org/css-masking-1/#the-mask-composite"],
		["radial-gradient: at syntax", [blink(), gecko()], "https://drafts.csswg.org/css-images-4/#radial-gradients"],
		["{rex, rch, cap, rcap, ic, ric, lh, rlh} units", [], "https://drafts.csswg.org/css-values-4/#font-relative-lengths"],
		["@when, @else", [], "https://drafts.csswg.org/css-conditional-5/#when-rule"],
		["color()", [webkit()], "https://drafts.csswg.org/css-color-5/#color-function"],
		["COLRv1 fonts", [blink(), gecko(experimental)], "https://github.com/googlefonts/colr-gradients-spec/blob/main/OFF_AMD2_WD.md"],
		["forced-color-adjust", [blink()], "https://drafts.csswg.org/css-color-adjust-1/#forced-color-adjust-prop"],
		[":dir()", [gecko(), blink(experimental)], "https://drafts.csswg.org/selectors-4/#the-dir-pseudo"],
		[":local-link", [], "https://drafts.csswg.org/selectors-4/#the-local-link-pseudo"],
		[":target-within", [], "https://drafts.csswg.org/selectors-4/#the-target-within-pseudo"],
		[":current, :past, :future", [], "https://drafts.csswg.org/selectors-4/#time-pseudos"],
		[":playing, :paused, :seeking", [], "https://drafts.csswg.org/selectors-4/#video-state"],
		[":buffering, :stalled", [], "https://drafts.csswg.org/selectors-4/#media-loading-state"],
		[":muted, :volume-locked", [], "https://drafts.csswg.org/selectors-4/#sound-state"],
		["logical operators in @media", [blink(experimental), gecko()], "https://drafts.csswg.org/mediaqueries-5/#media-conditions"],
		["font-family: ui-{serif, sans-serif, monospace, rounded}", [webkit()], "https://drafts.csswg.org/css-fonts-4/#ui-serif-def"],
		["text-wrap: balance", [webkit()], "https://drafts.csswg.org/css-text-4/#text-wrap"],
		["@supports at-rule()", [], "https://github.com/w3c/csswg-drafts/issues/6966"],
		["grid tracks animations", [webkit(experimental), gecko()], "https://drafts.csswg.org/css-grid-2/#track-sizing"],
		["{float, clear}: inline-{start, end}", [blink(experimental), gecko()], "https://drafts.csswg.org/css-logical/#float-clear"],
		["overflow: clip", [blink(), webkit(experimental), gecko()], "https://drafts.csswg.org/css-overflow-3/#overflow-properties"],
		["d: path()", [blink(), gecko()], "https://svgwg.org/svg2-draft/paths.html#TheDProperty"],
		["offset", [blink(), gecko(), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#offset-shorthand"],
		["offset-anchor", [blink(experimental), gecko(), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#offset-anchor-property"],
		["offset-position", [blink(experimental), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#offset-position-property"],
		["offset-{distance, rotate}", [blink(), gecko(), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#offset-distance-property"],
		["offset-path", [blink(), gecko(), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#offset-path-property"],
		["offset-path: ray()", [blink(), gecko(experimental), webkit(experimental)], "https://drafts.fxtf.org/motion-1/#funcdef-offset-path-ray"],
		["CSS extensions", [], "https://drafts.csswg.org/css-extensions-1/"],
		["text-indent: {hanging, each-line}", [blink(experimental), webkit(experimental)], "https://drafts.csswg.org/css-text-3/#text-indent-property"],
		["overflow-wrap: anywhere", [blink(), gecko()], "https://drafts.csswg.org/css-text-3/#overflow-wrap-property"],
		["variable units", [], "https://drafts.csswg.org/css-variables-2/#variable-units"],
		[":modal", [blink(experimental), gecko(experimental), webkit(experimental)], "https://drafts.csswg.org/selectors-4/#modal-state"],
	],
	javascript: [
		["type annotations", [], "https://tc39.es/proposal-type-annotations/"],
		["file system access", [blink()], "https://wicg.github.io/file-system-access/"],
		["file handling", [blink()], "https://wicg.github.io/manifest-incubations/#file_handlers-member"],
		["folder handling", [], "https://github.com/WICG/file-handling/issues/9"],
		["navigator.storage.getDirectory()", [blink(), webkit()], "https://fs.spec.whatwg.org/#sandboxed-filesystem"],
		["navigator.storage.estimate()", [blink(), gecko()], "https://storage.spec.whatwg.org/#storagemanager"],
		["navigator.storage.estimate(): usageDetails", [blink()], "https://jarryd999.github.io/quota-usage-details/#proposed-solution"],
		["navigator.userAgentData", [blink()], "https://wicg.github.io/ua-client-hints/#interface"],
		["WebGPU", [blink(experimental), webkit(experimental), gecko(experimental)], "https://gpuweb.github.io/gpuweb/"],
		["Array.prototype.{toReversed(), toSorted(), toSpliced(), with()}", [], "https://tc39.es/proposal-change-array-by-copy/"],
		["record & tuple", [], "https://tc39.es/proposal-record-tuple/"],
		["PDF generation", [], "https://github.com/whatwg/html/issues/7946"],
		["pipeline operator", [], "https://tc39.es/proposal-pipeline-operator/"],
		["Push", [blink(), webkit(experimental), gecko()], "https://w3c.github.io/push-api/"],
		["Notifications", [blink(), gecko()], "https://notifications.spec.whatwg.org/#api"],
		["CanvasRenderingContext2D.prototype.roundRect()", [blink()], "https://html.spec.whatwg.org/multipage/canvas.html#2dcontext:dom-context-2d-roundrect"],
		["Array.prototype.{groupBy(), groupByToMap()}", [blink(experimental), gecko(experimental)], "https://tc39.es/proposal-array-grouping/"],
		["worker modules", [blink(), webkit()], "https://html.spec.whatwg.org/multipage/workers.html#workertype"],
		["import maps", [blink(), gecko(experimental)], "https://wicg.github.io/import-maps/"],
		["import assertions", [blink()], "https://tc39.es/proposal-import-assertions/"],
		["requestPostAnimationFrame()", [], "https://wicg.github.io/request-post-animation-frame"],
		["Temporal", [webkit(experimental)], "https://tc39.es/proposal-temporal/"],
		["Navigation", [blink()], "https://wicg.github.io/navigation-api/"],
		["Sanitizer", [blink(experimental), gecko(experimental)], "https://wicg.github.io/sanitizer-api/"],
		["URLPattern", [blink()], "https://wicg.github.io/urlpattern/"],
		["local font access", [blink()], "https://wicg.github.io/local-font-access/"],
		["Eyedropper", [blink()], "https://wicg.github.io/eyedropper-api/"],
		["(De)CompressionStream", [blink()], "https://wicg.github.io/compression/"],
		["HID", [blink()], "https://wicg.github.io/webhid/"],
		["USB", [blink()], "https://wicg.github.io/webusb/"],
		["Serial", [blink()], "https://wicg.github.io/serial/"],
		["Bluetooth", [blink()], "https://webbluetoothcg.github.io/web-bluetooth/"],
		["background fetch", [blink()], "https://wicg.github.io/background-fetch/"],
		["handwriting recognition", [blink(experimental)], "https://wicg.github.io/handwriting-recognition/"],
		["background sync", [blink()], "https://wicg.github.io/background-sync/spec/"],
		["periodic background sync", [blink()], "https://wicg.github.io/periodic-background-sync/"],
		["speech recognition", [blink(), webkit(), gecko(experimental)], "https://wicg.github.io/speech-api/#speechreco-section"],
		["Color", [], "https://wicg.github.io/color-api/"],
		["access handle", [], "https://github.com/WICG/file-system-access/blob/main/AccessHandle.md"],
		["storage foundation", [blink(experimental)], "https://github.com/WICG/storage-foundation-api-explainer/blob/master/README.md"],
		["custom highlight", [blink(experimental)], "https://drafts.csswg.org/css-highlight-api-1/"],
		["shape detection", [blink(experimental)], "https://wicg.github.io/shape-detection-api/"],
		["clipboard read", [blink(), webkit()], "https://wicg.github.io/raw-clipboard-access"],
		["OffscreenCanvas", [blink(), gecko(experimental)], "https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface"],
		["shared workers", [blink(), webkit(experimental), gecko()], "https://html.spec.whatwg.org/multipage/workers.html#shared-workers-and-the-sharedworker-interface"],
		["requestIdleCallback", [blink(), gecko()], "https://w3c.github.io/requestidlecallback/#the-requestidlecallback-method"],
		["MIDI", [blink()], "https://webaudio.github.io/web-midi-api/"],
		["custom protocol handling", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers"],
		["CSS.customMedia()", [], "https://drafts.csswg.org/mediaqueries-5/#script-custom-mq"],
		["BeforeInstallPromptEvent", [blink()], "https://wicg.github.io/manifest-incubations/#beforeinstallpromptevent-interface"],
		["navigator.share()", [blink(), webkit(), gecko(experimental)], "https://w3c.github.io/web-share/#share-method"],
		["navigator.share(): files", [blink(), webkit()], "https://w3c.github.io/web-share/#dom-sharedata-files"],
		["share target", [blink()], "https://w3c.github.io/web-share-target/"],
		["background blur", [], "https://w3c.github.io/mediacapture-extensions/#exposing-mediastreamtrack-source-background-blur-support"],
		["spatial navigation", [], "https://drafts.csswg.org/css-nav-1/"],
		["indexedDB.databases()", [blink(), webkit()], "https://w3c.github.io/IndexedDB/#ref-for-dom-idbfactory-databases"],
		["layout transition primitives", [], "https://tabatkins.github.io/specs/layout-transitions/"],
		["shared element transitions (JavaScript)", [blink(experimental)], "https://github.com/WICG/shared-element-transitions/blob/main/explainer.md"],
		["ScrollTimeline", [blink(experimental)], "https://drafts.csswg.org/scroll-animations-1/#scrolltimeline-interface"],
		["canvas color spaces", [blink(experimental), webkit(experimental)], "https://html.spec.whatwg.org/multipage/canvas.html#2dcontext:dom-canvasrenderingcontext2dsettings-colorspace"],
		["CSS.registerProperty()", [blink()], "https://drafts.css-houdini.org/css-properties-values-api-1/#registering-custom-properties"],
		["CSS typed object model", [blink()], "https://drafts.css-houdini.org/css-typed-om-1/"],
		["animation worklet", [blink(experimental)], "https://drafts.css-houdini.org/css-animation-worklet-1/"],
		["CSS Parser API", [], "https://wicg.github.io/css-parser-api/"],
		["Font Metrics API", [], "https://drafts.css-houdini.org/font-metrics-api-1/"],
		["Box Tree API", [], "https://drafts.css-houdini.org/box-tree-api-1/"],
		["Painting API", [blink(), webkit(experimental)], "https://drafts.css-houdini.org/css-paint-api-1/"],
		["Layout API", [blink(experimental)], "https://drafts.css-houdini.org/css-layout-api-1/"],
		["import.meta.resolve()", [blink(experimental)], "https://html.spec.whatwg.org/multipage/webappapis.html#import-meta-resolve"],
	],
};
