
/* 
bun run main.ts
*/

const experimental = "experimental";
const prefixed = "prefixed";
const limitedSupport = "limited-support";

const blink = (...labels: string[]) => ({ engine: "blink", engineName: "Blink", labels });
const webkit = (...labels: string[]) => ({ engine: "webkit", engineName: "WebKit", labels });
const gecko = (...labels: string[]) => ({ engine: "gecko", engineName: "Gecko", labels });

export default {
	html: [
		["<selectlist>", [blink(experimental)], "https://open-ui.org/components/selectlist/"],
		["popover", [blink(), webkit(), gecko(experimental)], "https://html.spec.whatwg.org/multipage/popover.html#the-popover-attribute"],
		["theme-color", [blink(limitedSupport), webkit()], "https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color"],
		["<fencedframe>", [blink()], "https://wicg.github.io/fenced-frame/#the-fencedframe-element"],
		["<portal>", [blink(experimental)], "https://wicg.github.io/portals/#the-portal-element"],
		["iframe credentialless", [blink()], "https://wicg.github.io/anonymous-iframe/#specification"],
		["declarative shadow dom", [blink(), webkit()], "https://html.spec.whatwg.org/multipage/scripting.html#attr-template-shadowrootmode"],
		["focusgroup", [blink(experimental)], "https://open-ui.org/components/focusgroup.explainer"],
		['contenteditable="plaintext-only"', [blink(), webkit()], "https://html.spec.whatwg.org/multipage/interaction.html#attr-contenteditable-plaintextonly"],
		["URL Fragment Text Directives", [blink(), webkit()], "https://wicg.github.io/scroll-to-text-fragment/"],
		["JPEG XL images", [webkit(), gecko(experimental)], "https://arxiv.org/ftp/arxiv/papers/1908/1908.03565.pdf"],
		["SVG favicons", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/links.html#rel-icon"],
		["AV1 videos", [blink(), gecko()], "https://aomediacodec.github.io/av1-spec/"],
		["<model>", [webkit(experimental)], "https://immersive-web.github.io/model-element/"],
		["interactive-widget", [blink()], "https://drafts.csswg.org/css-viewport-1/#interactive-widget-section"],
		["is attribute", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/custom-elements.html#attr-is"],
		["<input type=checkbox switch>", [webkit(experimental)], "https://github.com/whatwg/html/issues/4180"],
		["<script blocking>", [blink()], "https://html.spec.whatwg.org/multipage/scripting.html#attr-script-blocking"],
	],
	css: [
		["backdrop-filter", [blink(), webkit(prefixed), gecko()], "https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty"],
		["mask-border", [blink(prefixed), webkit()], "https://drafts.fxtf.org/css-masking-1/#mask-borders"],
		["print-color-adjust", [blink(prefixed), webkit(), gecko()], "https://drafts.csswg.org/css-color-adjust-1/#print-color-adjust"],
		["user-select", [blink(), webkit(prefixed), gecko()], "https://drafts.csswg.org/css-ui-4/#content-selection"],
		["text-size-adjust", [blink(), webkit(prefixed), gecko(prefixed)], "https://drafts.csswg.org/css-size-adjust-1/"],
		["box-decoration-break", [blink(prefixed), webkit(prefixed), gecko()], "https://drafts.csswg.org/css-break-3/#break-decoration"],
		["-webkit-text-fill-color", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://compat.spec.whatwg.org/#the-webkit-text-fill-color"],
		["-webkit-text-stroke", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://compat.spec.whatwg.org/#the-webkit-text-stroke"],
		["paint-order for -webkit-text-stroke", [webkit(), gecko()], "https://svgwg.org/svg2-draft/painting.html#PaintOrder"],
		["-webkit-text-security", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266--webkit-text-security"],
		["cross-fade()", [blink(prefixed), webkit()], "https://drafts.csswg.org/css-images-4/#cross-fade-function"],
		["line-clamp", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://drafts.csswg.org/css-overflow-4/#line-clamp"],
		["element()", [gecko(prefixed)], "https://drafts.csswg.org/css-images-4/#element-notation"],
		["-webkit-box-reflect", [blink(prefixed), webkit(prefixed)], "https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariCSSRef/Articles/StandardCSSProperties.html#//apple_ref/doc/uid/TP30001266-SW16"],
		["{inline, block}-size: stretch", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://drafts.csswg.org/css-sizing-4/#valdef-width-stretch"],
		["initial-letter", [blink(), webkit(prefixed)], "https://drafts.csswg.org/css-inline-3/#sizing-drop-initials"],
		["margin-trim", [webkit()], "https://drafts.csswg.org/css-box-4/#margin-trim"],
		[":host-context()", [blink()], "https://drafts.csswg.org/css-scoping-1/#selectordef-host-context"],
		["view transitions", [blink()], "https://drafts.csswg.org/css-view-transitions-1/"],
		["@property", [blink(), webkit(), gecko(experimental)], "https://drafts.css-houdini.org/css-properties-values-api-1/#at-property-rule"],
		["filter()", [webkit()], "https://drafts.fxtf.org/filter-effects-1/#FilterCSSImageValue"],
		["relative color syntax", [blink(), webkit()], "https://drafts.csswg.org/css-color-5/#relative-colors"],
		["@starting-style", [blink()], "https://drafts.csswg.org/css-transitions-2/#defining-before-change-style"],
		["transition-behavior", [blink()], "https://drafts.csswg.org/css-transitions-2/#transition-behavior-property"],
		["@page", [blink(), gecko()], "https://drafts.csswg.org/css-page-3/#at-page-rule"],
		["masonry layout", [gecko(experimental)], "https://drafts.csswg.org/css-grid-3/#masonry-layout"],
		["anchor positioning", [blink(experimental)], "https://drafts.csswg.org/css-anchor-position-1/"],
		["gradient color spaces", [blink(), webkit(), gecko(experimental)], "https://drafts.csswg.org/css-images-4/#gradients"],
		["overflow-{block, inline}", [gecko()], "https://drafts.csswg.org/css-overflow-3/#logical"],
		["overflow-clip-margin", [blink(), gecko()], "https://drafts.csswg.org/css-overflow-3/#overflow-clip-margin"],
		["@container style()", [blink()], "https://drafts.csswg.org/css-contain-3/#typedef-query-in-parens"],
		["scroll progress timelines", [blink(experimental)], "https://drafts.csswg.org/scroll-animations-1/#scroll-timelines"],
		["view progress timelines", [blink(), gecko(experimental)], "https://drafts.csswg.org/scroll-animations-1/#view-timelines"],
		["content-visibility", [blink(), webkit(experimental), gecko(experimental)], "https://drafts.csswg.org/css-contain-2/#content-visibility"],
		["hanging-punctuation", [webkit()], "https://drafts.csswg.org/css-text-3/#hanging-punctuation-property"],
		["stepped value functions (round(), mod(), rem())", [blink(experimental), webkit(), gecko()], "https://drafts.csswg.org/css-values-4/#round-func"],
		["sign-related functions (abs(), sign())", [blink(experimental), webkit(), gecko()], "https://drafts.csswg.org/css-values-4/#sign-funcs"],
		["clip-path: external SVGs", [gecko()], "https://drafts.fxtf.org/css-masking-1/#the-clip-path"],
		["COLRv1 fonts", [blink(), gecko(experimental)], "https://github.com/googlefonts/colr-gradients-spec/blob/main/OFF_AMD2_WD.md"],
		["forced-color-adjust", [blink()], "https://drafts.csswg.org/css-color-adjust-1/#forced-color-adjust-prop"],
		["font-family: ui-{serif, sans-serif, monospace, rounded}", [webkit()], "https://drafts.csswg.org/css-fonts-4/#ui-serif-def"],
		["d: path()", [blink(), gecko()], "https://svgwg.org/svg2-draft/paths.html#TheDProperty"],
		["text-indent: {hanging, each-line}", [webkit(experimental)], "https://drafts.csswg.org/css-text-3/#text-indent-property"],
		["object-view-box", [blink()], "https://drafts.csswg.org/css-images-5/#the-object-view-box"],
		["scrollbar-color", [blink(), gecko()], "https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color"],
		["scrollbar-width", [blink(), gecko()], "https://drafts.csswg.org/css-scrollbars-1/#scrollbar-width"],
		["::-webkit-scrollbar", [blink(prefixed), webkit(prefixed)], "https://webkit.org/blog/363/styling-scrollbars/"],
		["::-webkit-slider-runnable-track", [blink(prefixed), webkit(prefixed)], "https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-runnable-track"],
		["::-webkit-slider-thumb", [blink(prefixed), webkit(prefixed)], "https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-slider-thumb"],
		["::-moz-range-track", [gecko(prefixed)], "https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track"],
		["::-moz-range-thumb", [gecko(prefixed)], "https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-thumb"],
		["::-moz-range-progress", [gecko(prefixed)], "https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-progress"],
		["math-shift", [blink()], "https://w3c.github.io/mathml-core/#the-math-shift"],
		["math-depth", [blink(), gecko()], "https://w3c.github.io/mathml-core/#the-math-script-level-property"],
		["orphans, widows", [blink(), webkit()], "https://drafts.csswg.org/css-break-3/#widows-orphans"],
		["overlay", [blink()], "https://drafts.csswg.org/css-position-4/#overlay"],
		["scrollbar-gutter", [blink(), gecko()], "https://drafts.csswg.org/css-overflow-3/#scrollbar-gutter-property"],
		["text-justify", [gecko()], "https://drafts.csswg.org/css-text-4/#propdef-text-justify"],
		["toggle", [blink(experimental)], "https://tabatkins.github.io/css-toggle/"],
		["text-wrap", [blink(), webkit(experimental), gecko()], "https://drafts.csswg.org/css-text-4/#text-wrap"],
		["text-wrap-style: pretty", [blink()], "https://drafts.csswg.org/css-text-4/#text-wrap-style"],
		["{rex, rch, cap, rcap, ric} units", [blink(), webkit()], "https://drafts.csswg.org/css-values-4/#font-relative-lengths"],
		["::spelling-error, ::grammar-error", [blink(), webkit(experimental)], "https://drafts.csswg.org/css-pseudo-4/#selectordef-spelling-error"],
		["@scope", [blink(), webkit(experimental)], "https://drafts.csswg.org/css-cascade-6/#scoped-styles"],
		["align-content in block containers", [blink(experimental), webkit(experimental)], "https://drafts.csswg.org/css-align-3/#distribution-block"],
		["line-grid", [], "https://drafts.csswg.org/css-line-grid-1/#line-grid-property"],
		["mix()", [], "https://drafts.csswg.org/css-values-5/#mix"],
		["@page margin boxes", [], "https://drafts.csswg.org/css-page-3/#margin-boxes"],
		["page-based counters", [], "https://drafts.csswg.org/css-page-3/#page-based-counters"],
		["column combinator", [], "https://drafts.csswg.org/selectors-4/#the-column-combinator"],
		[":nth-col(), :nth-last-col()", [], "https://drafts.csswg.org/selectors-4/#the-nth-col-pseudo"],
		["@custom-media", [], "https://drafts.csswg.org/mediaqueries-5/#custom-mq"],
		["toggle()", [], "https://drafts.csswg.org/css-values-5/#toggle-notation"],
		["cascade control", [], "https://tabatkins.github.io/specs/css-cascade-control/"],
		["linked parameters", [], "https://drafts.csswg.org/css-link-params-1/"],
		["@extend", [], "https://tabatkins.github.io/specs/css-extend-rule/#extend-rule"],
		["content-size", [], "https://tabatkins.github.io/specs/css-content-size/#content-size"],
		["@filter", [], "https://tabatkins.github.io/specs/css-filter-rule/#filter-rule"],
		["::slotted()", [], "https://drafts.csswg.org/css-scoping-1/#slotted-pseudo"],
		["scroll-start", [], "https://drafts.csswg.org/css-scroll-snap-2/#scroll-start"],
		[":snapped", [], "https://drafts.csswg.org/css-scroll-snap-2/#snapped"],
		["sign-related functions in calc()", [], "https://drafts.csswg.org/css-values-4/#sign-funcs"],
		["src()", [], "https://drafts.csswg.org/css-values-4/#funcdef-src"],
		["@when, @else", [], "https://drafts.csswg.org/css-conditional-5/#when-rule"],
		[":local-link", [], "https://drafts.csswg.org/selectors-4/#the-local-link-pseudo"],
		[":target-within", [], "https://drafts.csswg.org/selectors-4/#the-target-within-pseudo"],
		[":current, :past, :future", [], "https://drafts.csswg.org/selectors-4/#time-pseudos"],
		[":playing, :paused, :seeking", [], "https://drafts.csswg.org/selectors-4/#video-state"],
		[":buffering, :stalled", [], "https://drafts.csswg.org/selectors-4/#media-loading-state"],
		[":muted, :volume-locked", [], "https://drafts.csswg.org/selectors-4/#sound-state"],
		["@supports at-rule()", [], "https://github.com/w3c/csswg-drafts/issues/6966"],
		["CSS extensions", [], "https://drafts.csswg.org/css-extensions-1/"],
		["variable units", [], "https://drafts.csswg.org/css-variables-2/#variable-units"],
		["focus-group", [], "https://open-ui.org/components/focusgroup.explainer"],
		["caret-shape", [], "https://drafts.csswg.org/css-ui-4/#propdef-caret-shape"],
		["copy-into", [], "https://drafts.csswg.org/css-gcpm-4/#copy-into-heading"],
		["exclusions (wrap-flow & wrap-through)", [], "https://drafts.csswg.org/css-exclusions-1/"],
		["regions (flow-into & flow-from)", [], "https://drafts.csswg.org/css-regions-1/"],
		["rhythmic sizing", [], "https://drafts.csswg.org/css-rhythm-1/"],
	],
	"javascript-apis": [
		["speech recognition", [blink(prefixed), webkit(prefixed), gecko(experimental)], "https://wicg.github.io/speech-api/#speechreco-section"],
		["File and Directory Entries API", [blink(prefixed), webkit(prefixed), gecko(prefixed)], "https://wicg.github.io/entries-api/"],
		["HTMLSelectElement.prototype.showPicker()", [blink(), webkit(experimental), gecko()], "https://html.spec.whatwg.org/multipage/input.html#dom-select-showpicker"],
		["custom highlight", [blink(), webkit(), gecko(experimental)], "https://drafts.csswg.org/css-highlight-api-1/"],
		["canvas color spaces", [blink(), webkit()], "https://html.spec.whatwg.org/multipage/canvas.html#2dcontext:dom-canvasrenderingcontext2dsettings-colorspace"],
		["CSS.registerProperty()", [blink(), webkit(), gecko(experimental)], "https://drafts.css-houdini.org/css-properties-values-api-1/#registering-custom-properties"],
		["CSS typed object model", [blink(), webkit()], "https://drafts.css-houdini.org/css-typed-om-1/"],
		["file system access", [blink(limitedSupport)], "https://wicg.github.io/file-system-access/"],
		["FileSystemObserver", [blink(experimental)], "https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md"],
		["file handling", [blink(limitedSupport)], "https://wicg.github.io/manifest-incubations/#file_handlers-member"],
		["navigator.userAgentData", [blink()], "https://wicg.github.io/ua-client-hints/#interface"],
		["WebGPU", [blink(limitedSupport), webkit(experimental), gecko(experimental)], "https://gpuweb.github.io/gpuweb/"],
		["Navigation", [blink()], "https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigation-api"],
		["Sanitizer", [blink(experimental), gecko(experimental)], "https://github.com/WICG/sanitizer-api/blob/main/explainer.md"],
		["URLPattern", [blink()], "https://urlpattern.spec.whatwg.org/"],
		["local font access", [blink()], "https://wicg.github.io/local-font-access/"],
		["EyeDropper", [blink(limitedSupport)], "https://wicg.github.io/eyedropper-api/"],
		["HID", [blink()], "https://wicg.github.io/webhid/"],
		["USB", [blink()], "https://wicg.github.io/webusb/"],
		["Serial", [blink()], "https://wicg.github.io/serial/"],
		["Bluetooth", [blink()], "https://webbluetoothcg.github.io/web-bluetooth/"],
		["background fetch", [blink()], "https://wicg.github.io/background-fetch/"],
		["handwriting recognition", [blink(experimental)], "https://wicg.github.io/handwriting-recognition/"],
		["background sync", [blink()], "https://wicg.github.io/background-sync/spec/"],
		["periodic background sync", [blink()], "https://wicg.github.io/periodic-background-sync/"],
		["WebTransport", [blink(), gecko()], "https://w3c.github.io/webtransport/"],
		["WebXR", [blink(), webkit(experimental), gecko(experimental)], "https://immersive-web.github.io/webxr/"],
		["document.caretPositionFromPoint", [gecko()], "https://drafts.csswg.org/cssom-view-1/#dom-document-caretpositionfrompoint"],
		["document.caretRangeFromPoint (non-standard)", [blink(), webkit()], "https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint"],
		["barcode detection", [blink()], "https://wicg.github.io/shape-detection-api/#barcode-detection-api"],
		["face detection", [blink(experimental)], "https://wicg.github.io/shape-detection-api/#face-detection-api"],
		["text detection", [blink(experimental)], "https://wicg.github.io/shape-detection-api/text#api"],
		["clipboard read", [blink(), webkit()], "https://w3c.github.io/clipboard-apis/#dom-clipboard-read"],
		["clipboard write()", [blink(), webkit()], "https://w3c.github.io/clipboard-apis/#dom-clipboard-write"],
		["requestIdleCallback", [blink(), webkit(experimental), gecko()], "https://w3c.github.io/requestidlecallback/#the-requestidlecallback-method"],
		["MIDI", [blink()], "https://webaudio.github.io/web-midi-api/"],
		["custom protocol handling", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers"],
		["beforeinstallprompt event", [blink()], "https://wicg.github.io/manifest-incubations/#beforeinstallpromptevent-interface"],
		["navigator.share()", [blink(limitedSupport), webkit(), gecko(experimental)], "https://w3c.github.io/web-share/#share-method"],
		["navigator.share(): files", [blink(limitedSupport), webkit()], "https://w3c.github.io/web-share/#dom-sharedata-files"],
		["share target", [blink(limitedSupport)], "https://w3c.github.io/web-share-target/"],
		["background blur", [blink()], "https://w3c.github.io/mediacapture-extensions/#exposing-mediastreamtrack-source-background-blur-support"],
		["indexedDB.databases()", [blink(), webkit()], "https://w3c.github.io/IndexedDB/#ref-for-dom-idbfactory-databases"],
		["ScrollTimeline", [blink()], "https://drafts.csswg.org/scroll-animations-1/#scrolltimeline-interface"],
		["animation worklet", [blink(experimental)], "https://drafts.css-houdini.org/css-animation-worklet-1/"],
		["Painting API", [blink(), webkit(experimental)], "https://drafts.css-houdini.org/css-paint-api-1/"],
		["Layout API", [blink(experimental)], "https://drafts.css-houdini.org/css-layout-api-1/"],
		["document.fragmentDirective", [blink()], "https://wicg.github.io/scroll-to-text-fragment/#feature-detectability"],
		["document.fragmentDirective.createSelectorDirective()", [blink(experimental)], "https://github.com/WICG/scroll-to-text-fragment/blob/main/fragment-directive-api.md#webidl"],
		["EditContext API", [blink()], "https://w3c.github.io/edit-context/"],
		["Web Neural Network API", [blink(experimental)], "https://webmachinelearning.github.io/webnn/"],
		["Model Loader API", [blink(experimental)], "https://webmachinelearning.github.io/model-loader/"],
		["contentvisibilityautostatechange event", [blink(), gecko(experimental)], "https://drafts.csswg.org/css-contain-2/#content-visibility-auto-state-change"],
		["scrollend event", [blink(), gecko()], "https://drafts.csswg.org/cssom-view-1/#eventdef-document-scrollend"],
		["navigator.vibrate()", [blink(), gecko()], "https://w3c.github.io/vibration/"],
		["ambient light sensor", [blink(experimental)], "https://w3c.github.io/ambient-light/"],
		["badging ", [blink(limitedSupport), webkit(limitedSupport)], "https://w3c.github.io/badging/"],
		["deviceorientationabsolute event ", [blink(), gecko(experimental)], "https://w3c.github.io/deviceorientation/#deviceorientationabsolute"],
		["clipboard web custom formats ", [blink()], "https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md"],
		["compute pressure", [blink(experimental)], "https://w3c.github.io/compute-pressure/"],
		["contact picker", [blink(limitedSupport)], "https://w3c.github.io/contact-picker/"],
		["Content Index", [blink(limitedSupport)], "https://wicg.github.io/content-index/spec/"],
		["WebCodecs: video", [blink(), webkit()], "https://w3c.github.io/webcodecs/"],
		["WebCodecs: audio", [blink()], "https://w3c.github.io/webcodecs/"],
		["CookieStore", [blink()], "https://wicg.github.io/cookie-store/"],
		["battery status", [blink()], "https://w3c.github.io/battery/"],
		["Idle Detection", [blink()], "https://wicg.github.io/idle-detection/"],
		["is input pending", [blink()], "https://wicg.github.io/is-input-pending/"],
		["JS Self-Profiling", [blink()], "https://wicg.github.io/js-self-profiling/"],
		["measure memory", [blink()], "https://wicg.github.io/performance-measure-memory/"],
		["documentPicutreInPicuture", [blink()], "https://wicg.github.io/document-picture-in-picture/"],
		["Preferences API", [blink(experimental)], "https://wicg.github.io/web-preferences-api/"],
		["FileSystemObserver", [blink(experimental)], "https://github.com/whatwg/fs/blob/main/proposals/FileSystemObserver.md"],
		["CloseWatcher", [blink()], "https://html.spec.whatwg.org/multipage/interaction.html#the-closewatcher-interface"],
		["Document.parseHTMLUnsafe, {Element, ShadowRoot}.prototype.setHTMLUnsafe", [blink(experimental), webkit(experimental), gecko(experimental)], "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#unsafe-html-parsing-methods"],
		["Observable", [blink(experimental)], "https://wicg.github.io/observable/"],
		["custom element disabledFeatures", [blink(), gecko()], "https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api:js-get-4"],
		["custom state pseudo-class", [], "https://html.spec.whatwg.org/multipage/custom-elements.html#custom-state-pseudo-class"],
		["navigator.storage.estimate(): usageDetails", [], "https://github.com/jarryd999/quota-usage-details#proposed-solution"],
		["WebXR WebGPU binding", [], "https://github.com/immersive-web/WebXR-WebGPU-Binding/blob/main/explainer.md"],
		["folder handling", [], "https://github.com/WICG/file-handling/issues/9"],
		["PDF generation", [], "https://github.com/whatwg/html/issues/7946"],
		["requestPostAnimationFrame()", [], "https://wicg.github.io/request-post-animation-frame"],
		["Color", [], "https://wicg.github.io/color-api/"],
		["CSS.customMedia()", [], "https://drafts.csswg.org/mediaqueries-5/#script-custom-mq"],
		["spatial navigation", [], "https://drafts.csswg.org/css-nav-1/"],
		["{snapchanged, snapchanging} event", [], "https://drafts.csswg.org/css-scroll-snap-2/#snapchanged-and-snapchanging"],
		["layout transition primitives", [], "https://tabatkins.github.io/specs/layout-transitions/"],
		["CSS Parser API", [], "https://wicg.github.io/css-parser-api/"],
		["Font Metrics API", [], "https://drafts.css-houdini.org/font-metrics-api-1/"],
		["Box Tree API", [], "https://drafts.css-houdini.org/box-tree-api-1/"],
	],
	ecmascript: [
		["Atomics.waitAsync()", [blink(), webkit()], "https://tc39.es/ecma262/multipage/structured-data.html#sec-atomics.waitasync"],
		["{Object, Map}.groupBy()", [blink(), webkit(experimental), gecko()], "https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object.groupby"],
		["resizable (Shared)ArrayBuffer", [blink(), webkit()], "https://tc39.es/ecma262/multipage/structured-data.html#sec-arraybuffer.prototype.resize"],
		["Promise.withResolvers()", [blink(), webkit(experimental), gecko()], "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.withResolvers"],
		["Set methods", [blink(experimental), webkit(), gecko(experimental)], "https://tc39.es/proposal-set-methods/"],
		["import attributes", [webkit()], "https://tc39.es/proposal-import-attributes/"],
		["Temporal", [webkit(experimental)], "https://tc39.es/proposal-temporal/"],
		["Intl.Segmenter", [blink(), webkit(), gecko(experimental)], "https://tc39.es/ecma402/#segmenter-objects"],
		["type annotations", [], "https://tc39.es/proposal-type-annotations/"],
		["decorators", [], "https://tc39.es/proposal-decorators/"],
		["pipeline operator", [], "https://tc39.es/proposal-pipeline-operator/"],
		["record & tuple", [], "https://tc39.es/proposal-record-tuple/"],
	],
	webassembly: [
		["extended constant expressions", [blink(), gecko()], "https://github.com/WebAssembly/extended-const/blob/master/proposals/extended-const/Overview.md"],
		["garbage collection", [blink(), gecko()], "https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md"],
		["multiple memories", [blink(), gecko(experimental)], "https://github.com/WebAssembly/multi-memory/blob/master/proposals/multi-memory/Overview.md"],
		["relaxed SIMD", [blink(), gecko(experimental)], "https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/Overview.md"],
		["tail calls", [blink(), gecko()], "https://github.com/WebAssembly/tail-call/blob/master/proposals/tail-call/Overview.md"],
		["JS Promise Integration", [blink(experimental)], "https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md"],
		["memory64", [blink(experimental), gecko(experimental)], "https://github.com/WebAssembly/memory64/blob/master/proposals/memory64/Overview.md"],
		["type reflection", [blink(experimental), gecko(experimental)], "https://github.com/WebAssembly/js-types/blob/main/proposals/js-types/Overview.md"],
	],
};
